elao_enum:
    # Provide the enum classes for which you want to automatically generate & register Doctrine DBAL Types:
    # https://github.com/Elao/PhpEnums#doctrine
    doctrine:
        types:
            user_state: App\Service\User\UserState
            habit_state: App\Service\Habit\HabitState
            creation_habit_state: App\Service\Habit\CreationHabitState
