elao_enum:
    # Provide the enum classes for which you want to automatically generate & register Doctrine DBAL Types:
    # https://github.com/Elao/PhpEnums#doctrine
    doctrine:
        types:
            habit_state: App\Service\Habit\HabitState
            metric_type: App\Service\Metric\MetricType
