framework:
    workflows:
        user:
            type: 'state_machine'
            marking_store:
                type: 'method'
                property: 'state'
            supports:
                - App\Entity\User
            initial_marking: start
            places:
                - start
                - new_habit
            transitions:
                new_habit:
                    from: start
                    to: new_habit
