monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50
            channels: ["!php"]
        nested:
            type: rotating_file
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            max_files: 5
            filename_format: '{filename}-{date}'
            date_format: 'Y-m-d'
            channels: ["!php"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!php"]
        errors:
          type: rotating_file
          path: '%kernel.logs_dir%/%kernel.environment%_error.log'
          level: error
          max_files: 5
          filename_format: '{filename}-{date}'
          date_format: 'Y-m-d'
