services:
    App\Repository\UserRepository:
        factory: [ '@doctrine.orm.entity_manager', getRepository ]
        arguments:
            - App\Entity\User

    App\Repository\HabitRepository:
        factory: [ '@doctrine.orm.entity_manager', getRepository ]
        arguments:
            - App\Entity\Habit
