version: '3.9'

services:
  db:
    container_name: habit_db
    image: postgres:14.1
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./db:/var/lib/postgresql/data:rw

  php:
    container_name: habit_php
    image: bifidokk/habit:latest
    env_file: php_service.env
    depends_on:
      - db
    volumes:
      - habit_app:/var/www/habit
      - ./config/jwt/private.pem:/var/www/habit/config/jwt/private.pem:ro
      - ./config/jwt/public.pem:/var/www/habit/config/jwt/public.pem:ro

  nginx:
    container_name: habit_nginx
    image: bifidokk/habit-nginx:latest
    ports:
      - "${NGINX_PORT}:80"
    depends_on:
      - php
    volumes:
      - ./logs/nginx:/var/log/nginx:cached
      - habit_app:/var/www/habit

  redis:
    container_name: habit_redis
    image: redis:alpine
    volumes:
      - habit_redis_data:/data

  newrelic:
    container_name: habit_newrelic
    image: newrelic/php-daemon

volumes:
  habit_app:
  habit_redis_data:
