version: '3.9'
services:
  db:
    image: postgres:14.1
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - ./db:/var/lib/postgresql/data:rw
      - ./postgres/init:/docker-entrypoint-initdb.d

  php:
    build:
      context: ./php-fpm
      dockerfile: ./Dockerfile.dev
      args:
        PHP_XDEBUG_MODE: ${PHP_XDEBUG_MODE}
        PHP_XDEBUG_CLIENT_PORT: ${PHP_XDEBUG_CLIENT_PORT}
        PHP_XDEBUG_CLIENT_HOST: ${PHP_XDEBUG_CLIENT_HOST}
        SYMFONY_CLI_VERSION: 5.4.20
        NEW_RELIC_AGENT_LICENSE_KEY: ${NEW_RELIC_AGENT_LICENSE_KEY}
        NEW_RELIC_APP_NAME: ${NEW_RELIC_APP_NAME}
    ports:
      - "${PHP_PORT}:9001"
    volumes:
      - ../:/var/www/symfony:cached
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    ports:
      - '8081:80'
    volumes:
      - ../:/var/www/symfony
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx:cached
    depends_on:
      - php
      - db

  redis:
    image: redis:alpine

  daemon:
    platform: linux/x86_64
    image: newrelic/php-daemon
