version: '3.9'
services:
  db:
    platform: linux/x86_64
    image: mysql:8.0.22
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql

  php:
    build:
      context: ./php-fpm
      args:
        PHP_XDEBUG_MODE: ${PHP_XDEBUG_MODE}
        PHP_XDEBUG_CLIENT_PORT: ${PHP_XDEBUG_CLIENT_PORT}
        PHP_XDEBUG_CLIENT_HOST: ${PHP_XDEBUG_CLIENT_HOST}
        SYMFONY_CLI_VERSION: 4.23.2
    ports:
      - "${PHP_PORT}:9001"
    volumes:
      - ../:/var/www/symfony:cached
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    ports:
      - '8081:80'
    volumes:
      - ../:/var/www/symfony
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx:cached
    depends_on:
      - php
      - db

  redis:
    image: redis:alpine
