FROM php:8.5-fpm-alpine

RUN apk add --no-cache \
    coreutils \
    gettext \
    icu-dev \
    libpq-dev \
    libxslt-dev \
    libzip-dev \
    libsodium-dev \
    freetype-dev \
    libjpeg-turbo-dev \
    libpng-dev \
    linux-headers \
    autoconf \
    gcc \
    g++ \
    make \
    curl \
    tar \
    openssl

RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) \
        intl \
        pdo_pgsql \
        pgsql \
        xsl \
        zip \
        gd

RUN pecl install apcu && docker-php-ext-enable apcu
RUN pecl install redis && docker-php-ext-enable redis

ARG PHP_XDEBUG_MODE=""
ARG PHP_XDEBUG_CLIENT_PORT="9003"
ARG PHP_XDEBUG_CLIENT_HOST="host.docker.internal"

ENV PHP_XDEBUG_MODE=$PHP_XDEBUG_MODE \
    PHP_XDEBUG_CLIENT_PORT=$PHP_XDEBUG_CLIENT_PORT \
    PHP_XDEBUG_CLIENT_HOST=$PHP_XDEBUG_CLIENT_HOST

COPY xdebug.ini /tmp/xdebug.ini.template
RUN if [ "$PHP_XDEBUG_MODE" != "off" ] && [ -n "$PHP_XDEBUG_MODE" ]; then \
        echo "Installing Xdebug..." && \
        pecl install xdebug && \
        docker-php-ext-enable xdebug && \
        rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
        envsubst < /tmp/xdebug.ini.template > /usr/local/etc/php/conf.d/xdebug.ini && \
        echo "Xdebug installed and configured"; \
    fi
RUN rm -f /tmp/xdebug.ini.template

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer

RUN curl -sS https://download.newrelic.com/php_agent/archive/12.6.0.34/newrelic-php5-12.6.0.34-linux-musl.tar.gz | tar -C /tmp -zx && \
    export NR_INSTALL_USE_CP_NOT_LN=1 && \
    export NR_INSTALL_SILENT=1 && \
    /tmp/newrelic-php5-*/newrelic-install install && \
    rm -rf /tmp/newrelic-php5-* /tmp/nrinstall* && \
    sed -i \
        -e 's/"REPLACE_WITH_REAL_KEY"/\${NEW_RELIC_LICENSE_KEY}/' \
        -e 's/newrelic.appname = "PHP Application"/newrelic.appname = \${NEW_RELIC_APP_NAME}/' \
        -e 's/;newrelic.daemon.app_connect_timeout =.*/newrelic.daemon.app_connect_timeout=15s/' \
        -e 's/;newrelic.daemon.start_timeout =.*/newrelic.daemon.start_timeout=5s/' \
        /usr/local/etc/php/conf.d/newrelic.ini

ARG SYMFONY_CLI_VERSION
RUN wget https://github.com/symfony-cli/symfony-cli/releases/download/v$SYMFONY_CLI_VERSION/symfony-cli_linux_amd64.tar.gz \
    && tar -xzvf symfony-cli_linux_amd64.tar.gz \
    && chmod +x symfony \
    && mv symfony /usr/local/bin/

COPY symfony.ini /usr/local/etc/php/conf.d/
COPY symfony.pool.conf /usr/local/etc/php-fpm.d/symfony.pool.conf
RUN rm -f /usr/local/etc/php-fpm.d/www.conf* /usr/local/etc/php-fpm.d/docker.conf /usr/local/etc/php-fpm.d/zz-docker.conf

WORKDIR /var/www/symfony

CMD ["php-fpm"]