name: Deploy
on: workflow_dispatch
jobs:
  deploy:
    name: Deploy to prod
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v1
      -   name: Setup PHP
          uses: shivammathur/setup-php@master
          with:
            php-version: 8.0


